### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by skorecky**
Login is not working for some reason, not sure what's up with it if you have a minute to check it out. Didn't feel like digging at it too much

### CODE REVIEW

**Comment by mattpolito** [comment]
Let's use this as an exercise in doing atomic commits in a team setting.

For example you've got a few things going on here...

Adding in the twitter bootstrap stuff would be a separate commit so that if it was decided not to go with it, it's just a commit that could be avoided.

Also, I was trying to keep development dependencies to a minimum that's why the use of sqlite. Is there a reason you're wanting to add mysql in or are you just used to that being your dev env? This would also be a separate commit.

And the login stuff was not finalized yet... so let's talk about that sometime.

**Comment by skorecky** [comment]
Agreed. Sorry about that giant commit, kinda forgot about working with other people part ;) Noted!

**Comment by mattpolito** [comment]
now remember, that this is a conversation and you can change your commits and then add them to this conversation. and by the end we would hopefully have something to be merged in.

**Comment by skorecky** [comment]
not really sure how to split up a commit.

**Pull request closed without merging**
